---
- hosts: all
  name: Bootstrap Alma VM
  connection: local
  become: true
  tasks:

    - name: Add Public Keys
      ansible.posix.authorized_key:
        user: mrhoads
        state: present
        key: https://github.com/mrhoads.keys